#!/usr/bin/env bash
 //Run the Docker container
docker run -p 8080:80 -d -it holbertonschool/265-0
 //Access the running container
docker exec -it <container_id> /bin/bash
 //Install Apache if missing
apt-get update
apt-get install apache2 -y
 //Start Apache
service apache2 start
 //Create the index.html file
echo "Hello Holberton" > /var/www/html/index.html
 //Exit and verify
exit
curl 0:8080
Hello Holberton
 //Command Summary
docker exec -it <container_id> /bin/bash
apt-get update && apt-get install apache2 -y
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
