#!/usr/bin/env bash
# configure my apache file so that when querying the root to return Holberton school
apt update && apt install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
