#!/usr/bin/env bash
# configure my apache file so that when querying the root to return Holberton school

sudo apt-get update
sudo apt-get install apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton"
sudo service apache2 restart
