#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#    Listens on port 80.
#    Returns a page containing "Holberton School" when queried
#    at the root with a curl GET request.

# Update package list and install Nginx
apt-get update -y
apt-get install nginx -y 

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create an index.html file with the required content
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx service
service nginx restart
