#!/bin/bash

# Install Nginx if not already installed
apt-get update -y
apt-get install nginx -y

# Remove the default nginx HTML file
rm /var/www/html/index.nginx-debian.html

# Create a new HTML file with the required content
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure Nginx to listen on port 80 and redirect /redirect_me
echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx without using systemctl
service nginx restart


